### ISSUE TITLE
funny bug on collection pages: timeline does not update

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#944] opened 2020-07-17 21:00 UTC
it's always the same timeline :D I thought it was a question of loading but in fact it's really always the same time line, no matter the collection :)

![image](https://user-images.githubusercontent.com/32094266/87830424-44460f80-c881-11ea-83d9-a1b348f5d0bf.png)

**Comment by Bunoute** [comment] 2020-07-17 21:02
also, the number of articles in the collection does not correspond at all with the reality... but then, my connection is very weak and it may be also caused by that...

**Comment by PaulSchroeder** [comment] 2020-07-20 09:37
hi @Bunoute I can't reproduce the timeline bug. 

You can tell if it is loading a loading issue by checking the yellow line on top ... I'll fade out the graph while loading, as we do on other graphs within the app.

it could also be a temporary issue on the server. please check again if the bug is still there.

**Comment by danieleguido** [comment] 2020-07-27 11:18
It looks like it is fixed in dev at least!

**Closed by danieleguido** 2020-07-27 11:18 UTC
Labels: bug
