### ISSUE TITLE
on DEV: in ngram viewer: missing space and word in human readable summary

### ISSUE THREAD

**Issue by Bunoute** [impresso/impresso-frontend#942] opened 2020-07-17 09:00 UTC
"14,881 mentions of titanic in46,414 mentions of naufrage in 44,985 articles"
shoud be: 14,881 mentions of titanic in (SPACE) 46,414 ARTICLES mentions of naufrage in 44,985 articles

**Comment by danieleguido** [comment] 2020-07-23 06:43
closed as duplicate of #876

**Closed by danieleguido** 2020-07-23 06:43 UTC
Labels: wording
