### ISSUE TITLE
adjusted dates in search pill are ignored

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#957] opened 2020-08-13 13:07 UTC
https://impresso-project.ch/app/search?sq=CggQAhgWKgJMVQoCGAIKDhACGAcgASoGbWVyemlnCjIQAhgKKiwxOTM2LTEyLTE3VDAwOjAwOjAwWiBUTyAxOTQ0LTA4LTIwVDIzOjU5OjU5Wg%3D%3D&p=1

1. selected dates in timeline 
2. ran query
3. adjusted in search pill, reran query

**Comment by theorm** [comment] 2020-08-17 09:13
I could not reproduce (I got an error which I know was fixed in dev)  but I suspect if this problem is different to the error issue then it is most likely fixed in dev https://dev.impresso-project.ch/app/search?sq=CggQAhgWKgJMVQoCGAIKDhACGAcgASoGbWVyemlnCjIQAhgKKiwxOTM2LTEyLTE2VDAwOjAwOjAwWiBUTyAxOTQ0LTA4LTIwVDIzOjU5OjU5Wg%3D%3D&p=1

**Comment by danieleguido** [comment] 2024-10-07 13:51
fixed in current dev version

**Closed by danieleguido** 2024-10-07 13:51 UTC
Labels: bug, to be closed, fixed
