### ISSUE TITLE
Backspace key triggers browser "Back" function when trying to edit a keyword

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#751] opened 2020-02-21 15:39 UTC
the most annoying bug so far in my experience :-)

happens in Search but also Word embeddings

**Comment by theorm** [comment] 2020-03-18 20:03
Which browser do you use @mduering ? I just tried in Chrome and it does not trigger navigation.

**Comment by mduering** [comment] 2020-03-19 05:58
@theorm I used Firefox but tried unsuccessfully to reproduce it now, so was fixed along the way - I will close this :-)

**Comment by mduering** [comment] 2020-03-24 09:25
it seems the problem persists with arrow keys in Firefox 74

**Comment by danieleguido** [comment] 2020-03-24 14:25
Cannot reproduce it in firefox 74. Can you do a screencast?

**Comment by danieleguido** [comment] 2020-08-05 13:29
Closing for now, please open t again if the problem still persists

**Closed by danieleguido** 2020-08-05 13:29 UTC
