### ISSUE TITLE
Collection labels not visible in Ngram search

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#1060] opened 2022-02-25 14:50 UTC
![image](https://user-images.githubusercontent.com/4408050/155735644-34a6e058-8ade-4e70-a2f6-c34529b4d470.png)

**Comment by danieleguido** [comment] 2024-03-27 21:31
done in #1199 (this is actually a duplicate of #1186 )

**Closed by danieleguido** 2024-03-27 21:31 UTC
Labels: bug
